- hosts: local
  roles:
  #- { role: list-orgs, tags: ["list-orgs-role"] }
  - { role: create-org, tags: ["create-org-role"] }
  - { role: create-datasource-zabbix, tags: ["create-datasource-zabbix-role"] }
  - { role: create-datasource-mysql, tags: ["create-datasource-mysql-role"] } 
  - { role: associate-admin-users, tags: ["associate-admin-users-role"] } 



#--extra-vars "org_name=common"

# export ANSIBLE_VAULT_PASSWORD=Password
# echo $ANSIBLE_VAULT_PASSWORD >> .vault_pass