- name: Verificando a exitencia da Org. "{{ org_name }}"
  uri:
    url: "{{ grf_server_host }}/api/orgs/name/{{ org_name | urlencode}}"
    headers:
      Content-Type: "application/json"
    user: "{{ grf_username }}"
    password: "{{ grf_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    body_format: json
  register: result

- name: Listando Usuários da Flowti
  uri:
    url: "{{ grf_server_host }}/api/orgs/40/users"
    headers:
      Content-Type: "application/json"
    user: "{{ grf_username }}"
    password: "{{ grf_password }}"
    method: GET
    force_basic_auth: yes
    status_code:
      - 200
    body_format: json
  register: response

- name: host
  debug:
    var: item.login
  loop: "{{ response.json }}"  
  when: item.login|lower  is search("flowti.com.br")

- name: Trazendo usuários Flowti para a Org. "{{ org_name }}"
  uri:
    url: "{{ grf_server_host }}/api/orgs/{{ result.json.id }}/users"
    headers:
      Content-Type: "application/json"
    user: "{{ grf_username }}"
    password: "{{ grf_password }}"
    method: POST
    force_basic_auth: yes
    status_code:
      - 200
      - 409
    body_format: json
    body: '{"loginOrEmail": "{{ item.login }}", "role": "{{ item.role }}"}'
  loop: "{{ response.json }}"
  when: item.login|lower  is search("flowti.com.br")

