- name: Verificando a exitencia da Org. "{{ org_name }}""
  uri:
    url: "{{ grf_server_host }}/api/orgs/name/{{ org_name | urlencode}}"
    headers:
      Content-Type: "application/json"
    user: "{{ grf_username }}"
    password: "{{ grf_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    body_format: json
  register: result

- name: Create MySQL datasource
  local_action:
    module: grafana_datasource
    name: "MySQL"
    grafana_url: "{{ grf_server_host }}"
    grafana_user: "{{ grf_username }}"
    grafana_password: "{{ grf_password }}"
    org_id: "{{ result.json.id }}"
    ds_type: "{{ datasource_type }}"
    ds_url: "{{ datasource_url }}"
    validate_certs: false
    database: "{{ database_name }}"
    user: "{{ database_user }}"
    additional_secure_json_data:
      password: "{{ database_pass }}"
    additional_json_data:
      connMaxLifetime: 300
  register: response

- debug:
    var: response.msg